name: CI
on: [push, pull_request]
jobs:
  test:
    name: CI
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dc: [dmd-latest, ldc-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install D Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - uses: actions/cache@v4
        with:
          path: ~/.dub
          key: ${{ matrix.dc }}-dub-${{ hashFiles('**/dub.selections.json') }}
          restore-keys: |
            ${{ matrix.dc }}-dub-
      - name: Run Tests
        run: dub test --override-config="vibe-d:tls/openssl"
